export enum TaskStage {
    DOCUMENTS_ISSUANCE = 'EMISSÃO DE DOCUMENTOS DE COLETA',
    COLLECTION = 'COLETA',
    DELIVERY_DOCUMENTS_ISSUANCE = 'EMISSÃO DE DOCUMENTOS DE ENTREGA',
    DELIVERY = 'ENTREGA',
    DELIVERY_CONFIRMATION = 'CONFIRMAÇÃO DE ENTREGA',
    BUDGET_CHECK = 'CONFERÊNCIA DE ORÇAMENTO',
}