name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  tests:
    uses: C0demain/logflow-backend/.github/workflows/unit-tests.yml@dev

  build:
    needs: [tests]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag logflow_server:$(date +%s)
