name: Push image to DockerHub by sprint
on:
  push:
    branches:
      - sprint-*
jobs:
    tests:
      uses: C0demain/logflow-backend/.github/workflows/unit-tests.yml@dev
    build:
      name: push docker image to docker hub
      needs: [tests]
      runs-on: ubuntu-latest
      steps:
        - name: check repository
          uses: actions/checkout@v4

        - name: login to docker hub
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}
          
        - name: build and push docker image to registry
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ${{secrets.DOCKERHUB_USERNAME}}/logflow-api:${{github.ref_name}}

        